name: model-ranking

channels:
  - pytorch
  - conda-forge
  - nvidia
  - nodefaults

dependencies:
  - h5py
  - imageio
  - ipykernel
  - matplotlib
  - numpy
  - pathlib
  - pip
  - plant-seg
  - pydantic
  - pytest
  - pytorch
  - pytorch-cuda=12.1
  - pyyaml
  - python-elf
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - tensorboard
  - torch_em
  - tqdm
  - typer
  - typing
  - wandb

  - pip:
      - torcheval
      - -e .
      - -e /g/kreshuk/talks/pytorch-3dunet

