name: model-rank

channels:
  - pytorch
  - conda-forge
  - nvidia
  - nodefaults

dependencies:
  - h5py
  - imageio
  - ipykernel
  - matplotlib
  - numpy
  - pathlib
  - pip
  - plant-seg
  - pydantic
  - pytest
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pyyaml
  - python-elf
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - tensorboard
  - torchvision=0.20.1
  - torch_em
  - tqdm
  - typer
  - typing
  - wandb

  - pip:
      - -e .
      - git+https://github.com/Josh-Talks/pytorch-3dunet.git@1.8.7-model_ranking#egg=pytorch3dunet
      - git+https://github.com/Josh-Talks/adabn-pytorch.git@v1.0-model-ranking#egg=adabn
      - torcheval
