name: model-rank-2

channels:
  - pytorch
  - conda-forge
  - nvidia
  - nodefaults

dependencies:
  - python=3.11
  - h5py
  - imageio
  - ipykernel
  - matplotlib
  - numpy
  - pathlib
  - pip
  - plant-seg
  - pydantic
  - pytest
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pyyaml
  - python-elf
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools=80.9.0
  - tensorboard=2.19.0
  - torchvision=0.20.1
  - tqdm
  - typer
  - typing
  - wandb

  - pip:
      - -e .
      - -e /g/kreshuk/lage/pytorch-3dunet
      - -e /g/kreshuk/lage/adabn-pytorch
      - -e /g/kreshuk/lage/torch_em
      - torcheval
