### Target Datasets
target_datasets:
  - name: VNC

### Source Models
source_models:
  - source_name: EPFL
    model_name: EtoV_DO_a02_model1
  - source_name: Hmito
    model_name: HtoV_DO_a02_model1
  - source_name: Rmito
    model_name: RtoV_DO_a02_model1

### Perturbation Settings

# Feature perturbations
feature_perturbations:
  random_seed: 42
  layers: [0]
  spatial_dropout: True
  perturbation_types:
    - "None"
    - "DropOutPerturbation"
  dropOut_rates:
    - 0.005
    - 0.01
    - 0.05
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
  featureDrop_thresholds: null
  featureNoise_ranges: null 

# Input Augmentations
input_augs:
    none: []

### General Run Settings
overwrite_yaml: True
segmentation_mode: semantic
run_mode: full
data_base_path: /scratch/talks/data
model_dir_path: /g/kreshuk/talks/segmentation_ModelSelection/experiments
summary_results:
  overwrite_scores: False

# Output Settings
output_settings:
  result_dir: resized
  approach: feature_perturbation_consistency
  base_dir_path: /g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria


### Performance and Consistency evaluation settings
eval_settings:
  name: MultiClassF1
  eval_save_key: hard_f1
  overwrite_score: True

consistency_settings:
  name: Hamming-Distance
  save_key: HD_consis
  save_mask: True
  mask_threshold: 0.5
  overwrite_score: True
