 ### Target Datasets
target_datasets:
  - name: Rmito

### Source Models
source_models:
  - source_name: EPFL
    model_name: EtoRm_model5
    model_type: UNet2d_as3d
  - source_name: EPFL
    model_name: EtoRm_model_NA2
    model_type: UNet2d_as3d
  - source_name: EPFL
    model_name: EtoRm_model_Res1
    model_type: ResidualUNet2D_as_3D
  
### Perturbation Settings

# Feature perturbations
feature_perturbations: null

# Input Augmentations
input_augs:
  none: []

### General Run Settings
overwrite_yaml: False
segmentation_mode: semantic
run_mode: pred_eval
data_base_path: /scratch/lage/data/mitochondria
model_dir_path: /g/kreshuk/lage/model_checkpoints/mitochondria

summary_results:
  overwrite_scores: False
  filter_patches: False
  eval_key: F1_eval
  consis_key: EI_consis
  save_name_postfix: _full

# Output Settings
output_settings:
  result_dir: predictions
  approach: adabn_pct75
  output_folder: null
  base_dir_path: /g/kreshuk/lage/results/pred_eval


### Performance and Consistency evaluation settings
eval_settings:
  name: MultiClassF1
  eval_save_key: F1_eval
  overwrite_score: False

consistency_settings: null
