 ### Target Datasets
target_datasets:
  - name: Hmito
  - name: Rmito

### Source Models
source_models:
  - source_name: EPFL
    model_name: E_model5
    model_type: UNet2d_as3d
  - source_name: EPFL
    model_name: E_model_NA2
    model_type: UNet2d_as3d
  - source_name: EPFL
    model_name: E_model_Res1
    model_type: ResidualUNet2D_as_3D

# Feature perturbations
feature_perturbations: null

# Input Augmentations
input_augs:
  none: []

### General Run Settings
overwrite_yaml: True
segmentation_mode: semantic
run_mode: adaptive_batchnorm
data_base_path: /scratch/lage/data/mitochondria
model_dir_path: /scratch/lage/model-checkpoints/semantic/mitochondria/

summary_results:
  overwrite_scores: False

# Output Settings
output_settings:
  result_dir: checkpoints_adabn_pct75
  approach: adabn_pct75
  output_folder: null
  base_dir_path: /g/kreshuk/lage/model_checkpoints/mitochondria

### Performance and Consistency evaluation settings
eval_settings: null

consistency_settings: null

data_fraction: 0.75