wandb:
  project: EPFL
  name: model_test
  mode: online

model_path: TODO 

model_key: model_state

summary_results:
  filter_patches: null
  output_path: TODO
  eval_key: F1_eval
  consis_key: null
  overwrite_scores: false
  save_name_postfix: ''

model:
  name: UNet2D
  in_channels: 1
  out_channels: 1
  layer_order: bcr
  f_maps: 32
  final_sigmoid: true
  feature_return: false
  is_segmentation: true
  feature_perturbation: null

predictor:
  name: PatchWisePredictor
  save_segmentation: false
  min_size: null
  layer_id: null
  zero_largest_instance: false
  no_adjust_background: false

loaders:
  dataset: StandardHDF5Dataset
  batch_size: 32
  num_workers: 8
  raw_internal_path: raw
  label_internal_path: labels
  global_normalization: true
  global_percentiles: null
  output_dir: TODO- where saving predictions
  test:
    file_paths:
    - PAth to test dataset
    slice_builder:
      name: SliceBuilder
      patch_shape: [1, 256, 256]
      stride_shape: [1, 256, 256]
      halo_shape: [0, 32, 32]
    transformer:
      raw:
      - name: Normalize
      - name: ToTensor
        expand_dims: true
    roi:
    - - 0
      - 150
    - - 0
      - 1280
    - - 0
      - 1280

evaluation:
  eval_dataloader:
    eval_dataset:
      name: StandardEvalDataset
      aug_name: predictions
      pred_path: [predictions path]
      gt_path:
      - gt path
      pred_key: predictions
      gt_key: labels
      patch_key: patch_index
      roi:
      - - 0
        - 150
      - - 0
        - 1280
      - - 0
        - 1280
      ignore_index: null
      ignore_path: null
      ignore_key: null
      convert_to_binary_label: false
      convert_to_boundary_label: false
      relabel_background: false
      min_object_size: null
      instance_zero_background: false
      zero_largest_instance: false
    batch_size: 32
    num_workers: 8
  eval_metric:
    eval_save_key: F1_eval
    overwrite_score: true
    name: MultiClassF1
    threshold: 0.5

