name: HtoE_F_model1
output_root_path: /g/kreshuk/talks/model_ranking_results/Self-Finetuning/Mitochondria/Hmito_to_EPFL/feature_perturbation/DO_a02

training_cfg:
  lr: 1e-4
  n_iterations: 250

data_cfg:
  unsupervised_train_paths: ["/scratch/talks/data/EPFL/train.h5"]
  unsupervised_val_paths: ["/scratch/talks/data/EPFL/val.h5"]
  patch_shape: [1, 256, 256]
  supervised_train_paths: null
  supervised_val_paths: null
  raw_key: "raw" 
  raw_key_supervised: null
  label_key: null
  batch_size: 32
  n_samples_train: null
  n_samples_val: null

model_cfg:
  model:
    name: UNet2d_as3d
    in_channels: 1
    out_channels: 1
    layer_order: bcr
    f_maps: 32
    final_sigmoid: true
    feature_return: false
    is_segmentation: true
    feature_perturbation: null
  source_checkpoint: "/g/kreshuk/talks/segmentation_ModelSelection/experiments/Hmito/BatchNorm/Hm_model3/best_checkpoint.pytorch"

pseudo_labeler_cfg:
  name: "model_consistency"
  consistency_threshold: 0.5
  seg_params:
    name: "semantic"
  consistency_metric:
    name: "EI"
    threshold: 0.5
    save_key: null
    save_mask: null
    mask_threshold: 0.5
    overwrite_score: null
  perturbed_model_config:
    name: UNet2d_as3d
    in_channels: 1
    out_channels: 1
    layer_order: bcr
    f_maps: 32
    final_sigmoid: true
    feature_return: false
    is_segmentation: true
    feature_perturbation:
      layers: [0]
      random_seed: 42
      name: DropOutPerturbation
      drop_rate: 0.2
      spatial_dropout: true

